# Generated by Django 5.0.4 on 2024-04-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('nit', 'NIT'), ('cc', 'Cédula de ciudadanía')], max_length=3)),
                ('identificacion', models.CharField(max_length=20)),
                ('fechaingreso', models.DateField()),
                ('salarioMensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apiRest.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cell', 'Celular'), ('tel', 'Teléfono')], max_length=4)),
                ('numero', models.CharField(max_length=20)),
                ('indicativo', models.CharField(max_length=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='apiRest.empleado')),
            ],
        ),
    ]
